apiVersion: v1
kind: Service
metadata:
  name: cloudopsx-frontend
  labels:
    app: cloudopsx-frontend
spec:
  type: LoadBalancer
  selector:
    app: cloudopsx-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32383
