apiVersion: v1
kind: Service
metadata:
  name: cloudopsx-frontend-service
  namespace: default
spec:
  selector:
    app: cloudopsx-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
